# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nakul Pacheriwala
title: Data Scientist / Machine Learning Engineer
email: nakool24@gmail.com
# email_title: Email (Email title override)
phone: +1 (469) 943 7674
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username:
github_username: Nakul24-1
stackoverflow_username: "10285756"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: nakul-pacheriwala
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ
#huggingface: https://huggingface.co/Nakul24

# Additional icon links
additional_links:
  - title: Huggingface
    icon:
    # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
    url: https://huggingface.co/Nakul24
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Versatile honors graduate from NMIMS University, currently pursuing masters in computer science at New York University.
  Experienced in developing and testing prediction models, while also visualizing and explaining the results via interactive dashboards.
  Looking to solve business problems using data-driven models which would help the management make informed decisions.

content:
  - title: Technical Skills
    layout: list
    content:
      - layout: left
        sub_title: >
          Programming Languages :
        description: |
          R, Python, SQL, C++, Hadoop, Spark, Git, Java, Solidity, MATLAB, SAS
      - layout: left
        sub_title: >
          Web Development :
        description: |
          HTML, CSS, Bootstrap, JavaScript, D3.js, Flask, Streamlit
      - layout: left
        sub_title: >
          Machine Learning Technologies :
        description: |
          Supervised Learning, Unsupervised Learning, Reinforcement Learning, PCA, t-SNE, Neural Networks (CNN, RNN, LSTM, GAN), Large Language Models, BERT, T5, LLaMa, SHAP, LIME
      - layout: left
        sub_title: >
          Libraries and API:
        description: |
          Pandas, Numpy, Scipy, OpenCV, Scikit-learn, Beautiful Soap, TensorFlow, PyTorch, Keras, MySQL
      - layout: left
        sub_title: >
          Other Skills  :
        description: |
          Microsoft Excel, AWS, Azure, ETL pipelines, Regression Analysis, Docker, MongoDB, EDA, Google Analytics, Named Entity Recognition (NER), Data Mining, MapReduce, DynamoDB

  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Systematic Trading of Cryptocurrencies
        description: |
          - Devised a pairs trading strategy for cryptocurrencies by identifying stationary pairs through statistical tests.
          - Implemented risk management techniques and optimized overall portfolio performance which resulted in a Sharpe ratio of 6.15.
          - Engineered a simple Random Forest model, accessible at https://nakul24-pairs-crypto.streamlit.app/Random_Forest.
      - layout: left
        border: weak
        title: Predicting M&A targets for abnormal portfolio returns
        description: |
          - Built a predictive model for Mergers and Acquisitions (M&A) target identification, achieving an impressive ROC AUC of 0.83 in predicting target companies to produce an abnormal return for investors.
          - Achieved 36.6% F1 score improvement by engineering features leveraging data collected using API.
          - Recommended investment strategies to generate a cumulative profit of 66% over 2.5 years from Jan 2020 till 21st Nov 2022.
      - layout: left
        border: weak
        title: YC Chatbot
        description: |
          - Developed a multilingual DialoGPT-based language model built using conversation data that includes Hindi and English.
          - Designed a discord bot which utilizes the model and deployed it using Heroku and Accelerated Inference API to generate responses with a low perplexity score of 3.21.
          - Deployed a scalable conversational AI, chat with multiple users concurrently and provides customized responses to every user.
      - layout: left
        border: weak
        title: Panacea – a mental health analysis tool
        description: |
          - Led development of NLP-based real-time analytics dashboard predicting probabilities of depression and anxiety, offering vital insights into user's mental state.
          - Hosted the streamlit application as containers using ECS and Load Balancer which was secured using AWS Cognito.
          - Utilized Lambda and API Gateway to connect the frontend with the S3 bucket and Sagemaker Endpoint.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: SchoolJoy, New York
        sub_title: AI Engineer
        caption: August 2023 – Present
        description: |
          - Designed and deployed a career guidance chatbot anticipated to provide real-time, tailored career advice to students and improve engagement with educational resources.
          - Developed and implemented a suite of AI-driven applications for educators and administrators, enhancing user experience by enabling the creation, launch, and use of educational apps through an intuitive interface.
          - Orchestrated deployment pipelines on Azure, leveraging Docker, Azure Kubernetes Service (AKS), and FastAPI, which established a robust, scalable environment for continuous integration and deployment of AI applications.
          - Innovated "Quests AI," a cutting-edge tool designed to autonomously generate adaptive learning quests for students, aiming to personalize education and improve learning outcomes.
      - layout: left
        title: NYU Vertically Integrated Projects (VIP), New York
        sub_title: Lead Researcher (Merger & Acquisition Outcome Prediction)
        caption: August 2022 – May 2023
        description: |
          - Successfully obtained data from various sources including Refinitiv, Bloomberg and Wikidata to support research objectives.
          - Led training and evaluation of the new GraphSAGE model (Refinitiv), resulting in 5 percent increase in performance compared to the original Wikidata model in predicting probability of M&A activity between two companies.
          - Facilitated regular team meetings, fostering a platform for brainstorming, problem-solving, and progress updates, resulting in enhanced collaboration among team members.
      - layout: left
        title: Dhandhania Infotech Pvt Ltd, India
        sub_title: Data Scientist
        caption: March 2020 – March 2021
        description: |
          - Prepared interactive dashboard to visualize applicant personality traits, aiding HR team in eliminating unsuitable candidates.
          - Designed and performed A/B tests to check the effectiveness of prediction models and t-tests to check the significance of results.

  - title: Education
    layout: list
    content:
      - layout: left
        title: New York University, Tandon School of Engineering, NY
        sub_title: Master of Science in Computer Science, GPA: 3.83
        caption: 2021 – 2023
        description: |
          Relevant Coursework: Data Science for Business, Big Data, Computer Vision, Cloud Computing, Blockchain, Systematic Investing
      - layout: left
        title: Narsee Monjee Institute of Management Studies (NMIMS), Mumbai
        sub_title: Bachelor of Technology in Computer Engineering (Hons)
        caption: 2017 – 2021
        description: |
          Relevant Coursework: Probability and Statistics, Business Visualization, Predictive Modelling, Artificial Intelligence, Operations Research, and Database Management Systems, Data Structures and Algorithms

  - title: Courses and Certifications
    layout: list
    content:
      - layout: left
        title: Minors in Machine Learning and Data Analytics
        description: |
          2-year minor degree in collaboration with NMIMS, Coursera and IBM
      - layout: left
        title: CS50 AI
        description: |
          AI online certification course on EdX | Harvard University
      - layout: left
        title: Analytics Edge
        description: |
          online course on EdX | Massachusetts Institute of Technology

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
