# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nakul Pacheriwala
title: Data Scientist / Machine Learning Engineer
email: nakool24@gmail.com
# email_title: Email (Email title override)
phone: +1 (469) 943 7674
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: 
github_username:  Nakul24-1
stackoverflow_username: "10285756"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: nakul-pacheriwala
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ
huggingface: https://huggingface.co/Nakul24

# Additional icon links
additional_links:
- title: Link name
  icon: 
  # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: https://huggingface.co/Nakul24
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Highly skillful and meticulous honours graduate from NMIMS University, currently pursuing masters in computer science at New York University.
  Experienced in developing and testing prediction models, while also visualizing and explaining the results via interactive dashboards.
  Looking to solve business problems using data-driven models which would help the managament make better decisions.



content:
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork* 

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Mental Health Analysis
        link: https://github.com/Nakul24-1/Mental-Health-Cloud
        link_text: Github page for project
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/Nakul24-1/Mental-Health-Cloud
        quote: >
          Short overview of the project
        description: | # this will include new lines to allow paragraphs
          - Led a team to deploy a real-time analytics dashboard which predicts the current mental state and displays the user history 
          - Hosted the streamlit application on AWS as containers using ECS and Load Balancer which was secured using AWS Cognito 
          - Built a pipeline that takes user input from front-end and outputs the prediction in less than 1 ms
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Emotion Cause Recognition
        link: https://github.com/Nakul24-1/Mental-Health-Cloud
        link_text: Github page for project
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/Nakul24-1/Mental-Health-Cloud
        quote: >
          Short overview of the project
        description: | # this will include new lines to allow paragraphs
          - Developed a RoBERTa and SpanBERT based question answering models (Available on Huggingface) to extract the emotion cause in each statement 
          - Performed exploratory data analysis in python to improve the explanation model by eliminating issues like class imbalance 
          - Presented the models as an alternative to SHAP and was proven better statistically using metrics like IoU


  - title: Experience
    layout: list
    content:
      - layout: right
        title: Dhandhania Infotech
        sub_title: Data Intern
        caption: March 2020 - March 2021
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: New York University, Tandon School of Engineering, New York
        sub_title: Masters of Science, Computer Science
        caption: 2021 - 2023
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
      - layout: top-right
        title: Narsee Monjee Institute of Management Studies (NMIMS
        sub_title: BTech (Hons), Computer Engineering
        caption: 2017 - 2021
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
